
version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: yarn start:dev
    ports:
      - 8080:8080
    volumes:
      - .:/app
    env_file:
      - .env
